# Generated by Django 5.2.18 on 2026-10-09 22:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('window_started', models.DateTimeField(auto_now_add=True)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('entity', models.CharField(max_length=40)),
                ('entity_id', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Grupo')),
                ('subject', models.CharField(max_length=100, verbose_name='Materia')),
                ('teachers', models.ManyToManyField(blank=True, limit_choices_to={'is_active': True, 'profile__role': 'docente'}, related_name='teaching_groups', to=settings.AUTH_USER_MODEL, verbose_name='Docentes')),
            ],
            options={
                'verbose_name': 'Grupo y materia',
                'verbose_name_plural': 'Grupos y materias',
                'ordering': ['name', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='portal.coursegroup', verbose_name='Grupo y materia')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cut', models.CharField(default='primer_parcial', max_length=40, validators=[django.core.validators.RegexValidator('\\A[a-z0-9_]{1,40}\\Z', 'Usa letras minúsculas, números o guion bajo.')], verbose_name='Corte')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Calificación')),
                ('attendance', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Asistencia (%)')),
                ('homework', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tareas (%)')),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='portal.enrollment')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['enrollment__student__code', 'cut'],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nombre')),
                ('starts_on', models.DateField(verbose_name='Inicio')),
                ('ends_on', models.DateField(verbose_name='Fin')),
                ('is_open', models.BooleanField(default=True, verbose_name='Captura abierta')),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
                'ordering': ['-starts_on'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_on__gte', models.F('starts_on'))), name='period_valid_dates')],
            },
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='portal.period', verbose_name='Periodo'),
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_version', models.PositiveIntegerField()),
                ('grade', models.DecimalField(decimal_places=2, max_digits=4)),
                ('attendance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('homework', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('threshold', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('model_version', models.CharField(max_length=64)),
                ('alert', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='predictions', to='portal.indicator')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('docente', 'Docente'), ('estudiante', 'Estudiante'), ('tutor', 'Tutor')], max_length=16, verbose_name='Rol')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('\\AEST-[0-9]{3,8}\\Z', 'Usa EST- seguido de 3 a 8 dígitos.')], verbose_name='Código')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000, verbose_name='Solicitud')),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Atendida', 'Atendida')], default='Pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.period')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='portal.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='portal.student', verbose_name='Estudiante'),
        ),
        migrations.CreateModel(
            name='SupportCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement', models.CharField(max_length=1000, verbose_name='Acuerdo visible al estudiante')),
                ('internal_notes', models.CharField(blank=True, max_length=1000, verbose_name='Nota interna')),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En seguimiento', 'En seguimiento'), ('Cerrado', 'Cerrado')], default='Pendiente', max_length=20, verbose_name='Estado')),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.period')),
                ('prediction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='case', to='portal.prediction')),
                ('request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='case', to='portal.helprequest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='portal.student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=1000, verbose_name='Avance visible al estudiante')),
                ('internal_notes', models.CharField(blank=True, max_length=1000, verbose_name='Nota interna')),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En seguimiento', 'En seguimiento'), ('Cerrado', 'Cerrado')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='followups', to='portal.supportcase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TutorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.period', verbose_name='Periodo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutor_assignments', to='portal.student', verbose_name='Estudiante')),
                ('tutor', models.ForeignKey(limit_choices_to={'is_active': True, 'profile__role': 'tutor'}, on_delete=django.db.models.deletion.PROTECT, related_name='tutor_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Tutor')),
            ],
            options={
                'verbose_name': 'Asignación de tutor',
                'verbose_name_plural': 'Asignaciones de tutores',
            },
        ),
        migrations.AddConstraint(
            model_name='indicator',
            constraint=models.UniqueConstraint(fields=('enrollment', 'cut'), name='unique_indicator_cut'),
        ),
        migrations.AddConstraint(
            model_name='indicator',
            constraint=models.CheckConstraint(condition=models.Q(('grade__gte', 0), ('grade__lte', 10)), name='indicator_grade_range'),
        ),
        migrations.AddConstraint(
            model_name='indicator',
            constraint=models.CheckConstraint(condition=models.Q(('attendance__gte', 0), ('attendance__lte', 100)), name='indicator_attendance_range'),
        ),
        migrations.AddConstraint(
            model_name='indicator',
            constraint=models.CheckConstraint(condition=models.Q(('homework__gte', 0), ('homework__lte', 100)), name='indicator_homework_range'),
        ),
        migrations.AddConstraint(
            model_name='indicator',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='indicator_positive_version'),
        ),
        migrations.AddConstraint(
            model_name='coursegroup',
            constraint=models.UniqueConstraint(fields=('name', 'subject', 'period'), name='unique_course_group'),
        ),
        migrations.AddConstraint(
            model_name='prediction',
            constraint=models.UniqueConstraint(fields=('indicator', 'indicator_version', 'model_version'), name='unique_prediction_version'),
        ),
        migrations.AddConstraint(
            model_name='prediction',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 1), ('threshold__gt', 0), ('threshold__lt', 1)), name='prediction_valid_score'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['admin', 'docente', 'estudiante', 'tutor'])), name='profile_valid_role'),
        ),
        migrations.AddConstraint(
            model_name='helprequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['Pendiente', 'Atendida'])), name='request_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'group'), name='unique_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='supportcase',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['Pendiente', 'En seguimiento', 'Cerrado']), ('version__gte', 1)), name='case_valid_status_version'),
        ),
        migrations.AddConstraint(
            model_name='followup',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['Pendiente', 'En seguimiento', 'Cerrado'])), name='followup_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='tutorassignment',
            constraint=models.UniqueConstraint(fields=('student', 'period'), name='one_tutor_per_student_period'),
        ),
    ]
